version: '3'
# создание сети ---------------------------
networks:
 netlemp:
   name: netlemp
   driver: bridge
   driver_opts:
    com.docker.network.bridge.name: ${IPV4_NETWORK:-br_web}
   ipam:
    config:
     - subnet: ${IPV4_NETWORK:-172.100.1}.0/24
       gateway: ${IPV4_NETWORK:-172.100.1}.1

# создание контейнеров
services:
# web сервер NGINX -------------------------
 nginx:
  container_name: nginx
  image: nginx:latest
  restart: always
  privileged: true
  networks: 
   netlemp:
    ipv4_address: ${IPV4_NETWORK:-172.100.1}.2
  hostname: nginx
  ports:
  - ${HTTP_PORT:-80}:80
#  - ${HTTPS_PORT:-443}:443
#  - 54321:54321/udp
#  - 54321:54321/tcp
  volumes:
  - ./nginx/conf:/etc/nginx/conf
  - ./nginx/conf.d:/etc/nginx/conf.d
  - ./nginx/sites-enabled:/etc/nginx/sites-enabled
  - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  - ./www:/var/www
  depends_on:
  - php82fpm
  - mariadb
# php-fpm ----------------------------
 php82fpm:
  container_name: php82fpm
  image: crunchgeek/php-fpm:8.2
  restart: always
  privileged: true
  networks: 
   netlemp:
    ipv4_address: ${IPV4_NETWORK:-172.100.1}.3
  volumes:
  - ./www:/var/www
  ports:
  - ${PHP_FPM_PORT:-9000}:9000
  depends_on:
  - mariadb
  environment:
    PHP_INI_PATH: ./nginx/php.ini
# сервер mariabd -----------------------
 mariadb:
  container_name: mariadb
  image: mariadb
  restart: always
  privileged: true
  networks: 
   netlemp:
    ipv4_address: ${IPV4_NETWORK:-172.100.1}.4
#  ports:
#  - ${MARIADB_PORT:-3306}:3306
  volumes:
  - ./mysql:/var/lib/mysql
  - ./www:/var/www
  environment:
    MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-mariadb}
    MARIADB_DATABASE: ${MARIADB_DATABASE:-db_terminal}
# phpMyAdmin ---------------------------
 phpmyadmin:
  container_name: phpmyadmin
  image: phpmyadmin
  restart: always
  privileged: true
  networks: 
   netlemp:
    ipv4_address: ${IPV4_NETWORK:-172.100.1}.5
#  ports:
#  - ${PHPMYADMIN_PORT:-85}:80
  environment:
    PMA_HOST: mariadb
  depends_on:
  - mariadb
# supervisor
 supervisor:
  container_name: supervisor
  build: ./app-conf/supervisor/
  networks: 
   netlemp:
    ipv4_address: ${IPV4_NETWORK:-172.100.1}.6
  volumes:
  - ./www/:/var/www/
  depends_on:
  - nginx
  - mariadb
  - php82fpm
#  ports:
#  - ${SUPERVISOR_PORT:-9001}:9001


